### PR TITLE
Mark SHA-1 subdomains as retired; move HTTP input below mixed content for column for balance.

### PR DESCRIPTION
**Pull request by lgarron**
@marumari, could you review?

### CODE REVIEW

**Comment by lgarron** [comment]
Also open to naming suggestions instead of `retired`. :-)

**Comment by marumari** [comment]
r+, but I think we need a more evocative emoji for the retired ones.  ☠️ seems like a fine option.

As for names, I don't mind "retired".  There's also "deprecated", "obsolete", and "what is the point of all this, really, in the end?"

**Comment by lgarron** [comment]
I'd like to avoid "deprecated" and "obsolete", because that implies we're talking about the security settings, not the subdomains themselves.

> ☠️ seems like a fine option.

What a cynical view of retirement. :-P

**Comment by lgarron** [comment]
Oh, I got this: :cd:deFUNKt🎶

**Comment by marumari** [comment]
Hahaha!  Let's do it!

**Comment by lgarron** [comment]
> Hahaha! Let's do it!

@marumari, alright, click on "Defunct" on the home page now. ;-)

**Comment by marumari** [comment]
Hahahahahahahahahaha

I highly approve of this use of company resources.

**Pull request merged**
