### PR TITLE
Update the mozilla sites to reflect current guidelines

### PR DESCRIPTION
**Pull request by marumari**
Note that these are not yet perfect, they're just closer to accurate:

- They all still want OCSP stapling enabled, which we don't have
- The modern recommendation says to use an ECDSA cert, which @lgarron would need to request and add to the certificate generator

### CODE REVIEW

**Comment by lgarron** [comment]
Sounds good to me, although we're on `nginx 1.10.0` now.

**Comment by marumari** [comment]
@lgarron, mind merging this?  I've got an update or two that I need to send, but this whole master:master thing is a pain.  :)

**Comment by lgarron** [comment]
Are they still up to date?

**Comment by marumari** [comment]
Yep, haven't been any significant changes recently.

**Comment by lgarron** [comment]
Also, could you squash? I would do it, but then you wouldn't be the author+committer.

**Comment by lgarron** [comment]
owait, maybe the GitHub option does that.

**Comment by lgarron** [comment]
Hmm, it works, but I'm still set as the committer.
If you object, feel free to squash and ask me to update and `push -f` ;-)

**Comment by marumari** [comment]
I'm not bothered by not being the committer.  :)

**Pull request merged**
