### PR TITLE
Add preact-cli and webpack-dev-server certificates to Known Bad

### PR DESCRIPTION
**Pull request by ngyikp**
Fixes https://github.com/chromium/badssl.com/issues/297

### CODE REVIEW

**Comment by ngyikp** [comment]
I signed it!

**Comment by lgarron** [comment]
Thanks!

This looks good to me, and I'll merge and deploy it once I can (#300).

Could you check on something for me, though? When these certificates are used for MitM, are they used as CA certificates to sign `localhost` certificates, or are they used directly?

**Comment by ngyikp** [comment]
Sorry for late reply

> When these certificates are used for MitM, are they used as CA certificates to sign localhost certificates, or are they used directly?

I'm not sure what this means? There are alternate test sites at https://badcert-preactcli.mike.works and https://badcert-webpack-dev-server.mike.works too, and the affected developer machines will be able to connect to those sites without warning

**Comment by lgarron** [comment]
> I'm not sure what this means?

`preact-cli` has `localhost` as SAN, which means that it can be used directly to serve HTTPS on localhost if it is trusted.
Similar with `webpack-dev-server`, except that the common name is only in the subject (which is deprecated in Chrome).

**Comment by lgarron** [comment]
> There are alternate test sites at https://badcert-preactcli.mike.works and https://badcert-webpack-dev-server.mike.works too, and the affected developer machines will be able to connect to those sites without warning

That's good to know – do the live badssl.com subdomains also connect?

**Pull request merged**
