### PR TITLE
Add ECC 256 to BadSSL (Local Only)

### PR DESCRIPTION
**Pull request by ByJamesBurton**

### CODE REVIEW

**Comment by ByJamesBurton** [comment]
I'm also thinking about creating another pull request with 384 ECC Key. (ecc384.badssl.com)

**Comment by lgarron** [comment]
Thanks for this! I probably won't be able to take a look until next year.

Could you squash the commits for now, though?

**Comment by ByJamesBurton** [comment]
Yes, I can squash the commits into about 6 file changes.

**Comment by ByJamesBurton** [comment]
Should I add the 384 bit key gen with it?

**Comment by ByJamesBurton** [comment]
Its local for now but I can change it to production for use on badssl.com domain.

**Comment by ByJamesBurton** [comment]
Pull Request #236 Replaces this request.

**Pull request closed without merging**
