### PR TITLE
Remove pregenerated self-signed chain

### LINKED ISSUE #359: Cert for self-signed.badssl.com has expired
The cert for https://self-signed.badssl.com/ appears to have expired yesterday (2018-08-07). I'll try to re-generate it and push the new cert live soon.

Coincidentally, this gives us a production cert for #150 if we wanted to add a new subdomain :-)

### PR DESCRIPTION
**Pull request by christhompson**
This removes the checked-in pre-generated self-signed certificate chain. This was preventing the self-signed cert from being re-generated during the `make certs-prod` step of deploying the site. After removing, it will be re-created (with a new validity period) on every deploy.

Fixes #359 (hopefully for good)

### CODE REVIEW

**Comment by christhompson** [comment]
@lgarron Does this look good to you? Thanks!

**Comment by christhompson** [comment]
Ahh hmm, I hadn't considered that some use cases might be relying on it being relatively static. Do you know of specific use cases that are affected by churn? The cases I'd considered (mainly remembering cert interstitial decisions) are equally covered by other invalid certificates like the expired cert.

If there are use cases for only rotating it every so often, I can instead check in a new self-signed cert and think about adding tooling to the deploy process to warn if it's expired.

**Comment by christhompson** [comment]
(Abandoning this -- we'll just track the expiration and regenerate in-tree when needed.)

**Comment by lgarron** [comment]
> Ahh hmm, I hadn't considered that some use cases might be relying on it being relatively static. Do you know of specific use cases that are affected by churn? The cases I'd considered (mainly remembering cert interstitial decisions) are equally covered by other invalid certificates like the expired cert.

Well, one case is if you've marked it as trusted it for testing. If we deploy while someone is testing like this, they'll unexpectedly see new failures.

**Pull request closed without merging**
