### PR TITLE
Add support for an extended validation certificate

### PR DESCRIPTION
**Pull request by april**
Here's the first go at it. It's a bit awkward, so feel free to let me know what you truly think.  :)

### CODE REVIEW

**Comment by lgarron** [comment]
LGTM. You sure you want `extended-validation` instead of `ev`?
(I'd be fine with adding a redirect from the latter to the former.)

**Comment by april** [comment]
I prefer to be verbose when possible, but I think adding a redirect seems like a fine idea. Lemme do that real quick.

**Comment by april** [comment]
I initially added ev.__DOMAIN__ to the cert, but then I realized that it would complicate the process of acquiring the production EV cert.

As such, I decided to use the normal wildcard cert for the redirect. Also if you think http://ev.badssl.com/ should redirect immediately to https://extended-validation.badssl.com/, I can make that tweak.

**Comment by lgarron** [comment]
Still looks good to me!

> As such, I decided to use the normal wildcard cert for the redirect. Also if you think http://ev.badssl.com/ should redirect immediately to https://extended-validation.badssl.com/, I can make that tweak.

I would slightly prefer `http://ev.badssl.com/`-> `https://ev.badssl.com/` -> `https://extended-validation.badssl.com/` but it doesn't sound super important.

**Comment by april** [comment]
Made the slight tweak to reflect @lgarron's most recent feedback. Thanks, @lgarron!

**Pull request merged**
