### PR TITLE
Update macOS install instructions

### PR DESCRIPTION
**Pull request by april**
Using the UI is for chumps and also way more steps.

### CODE REVIEW

**Comment by lgarron** [comment]
Hmm, I strongly prefer to use the UI to avoid shooting myself in the foot. If we tell other people where to use it, then they also know how to remove it.

Could you leave the old text, and offer the command as a shortcut "if you're already familiar with the process"?

**Comment by april** [comment]
Sure, lemme fix that up.

**Comment by april** [comment]
Okay, it's done. The old instructions had a lot of issues as well, and I think I've cleared those up as well.

**Comment by lgarron** [comment]
Thanks!

**Pull request merged**
