### PR TITLE
Add ecc.badssl.com

### PR DESCRIPTION
**Pull request by marumari**
Elliptic curve cryptography!  Heck yeah, probably!

### CODE REVIEW

**Comment by lgarron** [comment]
Don't we need an ECC cert for this?

**Comment by fishouttah20** [comment]
The commit uses EECDH in the ciphers list which includes both RSA and ECDSA cipher suites. Without an ECDSA cert only the RSA cipher suites can be negotiated but it would still work. This is assuming that the goal of ECC. is testing ECDHE key exchange and not ECDSA Certificates.

You could of course do ecdhe.badssl.com and ecdsa.badssl.com (and NothingButECC.badssl.com ;) )

**Comment by fishouttah20** [comment]
Also, it appears that Nginx STILL doesn't support dual certificates for a site (RSA+ECDSA), although Cloudflare and Wikimedia have their own patches to allow for it if you're on OpenSSL 1.0.2. Further information, hopefully it will be in the next release...http://forum.nginx.org/read.php?29,261089,261089#msg-261089

**Comment by lgarron** [comment]
News: Let's Encrypt ECDSA: https://twitter.com/letsencrypt/status/697504441075798016

screen shot 2016-03-02 at 00 48 38

**Comment by lgarron** [comment]
Obsoleted by #248.

**Pull request closed without merging**
