### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sleevi**
Fix a minor grammar nit - I suspect you are grateful for their graciousness, but I'm not sure if the CAs were grateful to issue the certificates ;)

### CODE REVIEW

**Comment by marumari** [comment]
I'm pretty sure that @robstradling was secretly happy, despite all the tears that I saw running down his face.

**Comment by lgarron** [comment]
Heh, thanks.

**Comment by robstradling** [comment]
@marumari lol.  I am secretly and publicly happy.  And gracious.  And graceful.  Oh wait, maybe not graceful.  ;-)

**Comment by roycewilliams** [comment]
You have to admit, there's something graceful about it, too. 

If there were a word in English that meant both, I'd submit a PR. :)

**Pull request merged**
