### PR TITLE
add missing domain incomplete-chain

### PR DESCRIPTION
**Pull request by greggles**
From #304.

### CODE REVIEW

**Comment by greggles** [comment]
I signed it!

🖊

**Comment by lgarron** [comment]
Thanks!

In the future, please make sure to test the change.
(The PR as-is completely breaks the dashboard.)

**Comment by greggles** [comment]
I am sorry about not testing first and breaking things :( Thanks for fixing the mistake.

I have to admit I read enough of the build instructions to know that it wasn't something I could easily do. I probably should have said I didn't test it and/or just submit the idea without the PR.

**Comment by lgarron** [comment]
> I have to admit I read enough of the build instructions to know that it wasn't something I could easily do.

May I ask which part? It's pretty much "install Docker and run `make`".

**Pull request merged**
