### PR TITLE
256 and 384 Bit ECC Subdomains from local to production tags

### PR DESCRIPTION
**Pull request by ByJamesBurton**
See issue #247 for more information about this pull request.

### CODE REVIEW

**Comment by lgarron** [comment]
I think I can get 3-year ECC certs from DigiCert, although adding more certs is a liability until we automate more.

@marumari, how do you feel about adding these two domains to prod for now?

@ByJamesBurton, could you update the commit and PR to reflect that this is about the ECC subdomains?

**Comment by ByJamesBurton** [comment]
I will update the commit and title to reflect the changes to the ECC subdomains.

**Comment by ByJamesBurton** [comment]
@lgarron Both title and commit text updated.

**Comment by lgarron** [comment]
> @lgarron Both title and commit text updated.

Thanks!

Sorry I didn't notice it the first time, but could you also move the content files from `domains-local-only` to `domains`?

**Comment by marumari** [comment]
Sure, I think you should go ahead and add them to production.  With nginx, you should be able to specify all three certs, and it should choose the correct one based on the cipher suite being used (although I'm not sure how it chooses between 256 and 384 in this case)

**Comment by lgarron** [comment]
> With nginx, you should be able to specify all three certs

We specify a single cert per domain using SNI right now. Any reason to change that?

**Comment by marumari** [comment]
For the domains that aren't about the cert itself, specifying both will allow nginx to use whatever cert type is specified first, if the client supports it.  So https://badssl.com/ would use the ECDSA certs most of the time and fallback to the RSA certs for clients that don't support ECDSA.

**Comment by lgarron** [comment]
> For the domains that aren't about the cert itself, specifying both will allow nginx to use whatever cert type is specified first, if the client supports it. So https://badssl.com/ would use the ECDSA certs most of the time and fallback to the RSA certs for clients that don't support ECDSA.

Ah, so you're saying we should support ECDSA for most domains by default, similar to how we [share ciphers by default](https://github.com/chromium/badssl.com/blob/master/nginx-includes/tls-defaults.conf)? That sounds like a job for a separate issue, since 1) that would require the ECC cert generation to wildcard certs, and 2) updating the default cert include to better-named than `wildcard-main` and includes multiple certs.

**Comment by ByJamesBurton** [comment]
Digicert gives an option to create duplicate certificates and I thought that as you are getting 3-year wildcard certificate maybe its time to replace some of the Comodo certs which are expiring this year.

**Comment by ByJamesBurton** [comment]
How did you get on with getting 3-year certificate from DigiCert?

**Comment by lgarron** [comment]
I didn't, because we didn't completely decide what to do. I'll start by getting them for these subdomains.

**Comment by lgarron** [comment]
Note: This doubles the number of valid certificates we maintain in production.

**Comment by ByJamesBurton** [comment]
This certificate will be a wilcard?

**Comment by marumari** [comment]
I honestly think we should just get a pair of ECDSA wildcard certs to run alongside the existing RSA wildcard cert.  I don't think we should go bonkers with subdomain certs.

**Comment by lgarron** [comment]
> I honestly think we should just get a pair of ECDSA wildcard certs to run alongside the existing RSA wildcard cert. I don't think we should go bonkers with subdomain certs.

Okay, sounds fair. Can one of you make a new PR to change the ECC cert generation to wildcards?

**Comment by ByJamesBurton** [comment]
@lgarron If @marumari doesn't mind. I will make a new PR to change the ECC cert generation to wildcards.

**Comment by marumari** [comment]
Be my guest, for I am swamped.

**Comment by lgarron** [comment]
> I will make a new PR to change the ECC cert generation to wildcards.

Thanks!

**Comment by ByJamesBurton** [comment]
@lgarron I'm going to use prime256v1 for the wildcards.

**Comment by ByJamesBurton** [comment]
#249 PR is uploaded and ready.

**Comment by lgarron** [comment]
The `root` serving paths also need to be updated. I'll do that.

**Comment by lgarron** [comment]
> The root serving paths also need to be updated. I'll do that.

(Just as a reminder, please make sure that `make test` works on the domains before sending a non-trivial PR.)

**Comment by ByJamesBurton** [comment]
> The root serving paths also need to be updated. I'll do that.
(Just as a reminder, please make sure that make test works on the domains before sending a non-trivial PR.)

I was too overconfident and presumptuous to think I could add this quite minor code without any actually testing which is what I normally do with any other PR I've created on BadSSL or elsewhere. I should have known from #236 that changing over from local to production wasn't just editing two lines (at first I thought the only changed needed was to update the tags `CHAINS_LOCAL_ONLY += to CHAINS_PROD +=`) it required a change to multiple files and even moving files from one section to another. One day, being overconfident is surely going to be my downfall. I've learn't big lesson here and I can sure you that it won't happen again. 

If you looked at my research papers and everything else I do in maths and cryptography ,you'd find them extremely different. Different to the point of the everything is tested from top to bottom, well written and never rushed.

**Comment by lgarron** [comment]
No worries, just test next time. :-)

**Pull request closed without merging**
